title: CRAIG T. CHOSNEY
logo: /assets/img/IMG_1068.jpg
description: Highly motivated and detail-oriented analyst with a passion for using data to improve business performance and customer experience
#show_downloads: true
theme: jekyll-theme-minimal
