title: CRAIG T. CHOSNEY
logo: /assets/img/headshot2025_2B.png
description: Highly motivated and detail-oriented analyst with a passion for using data to improve business performance and constituent experience
#show_downloads: true
theme: jekyll-theme-minimal
