title: Craig T. Chosney
logo: /assets/img/IMG_1068.jpg
description: Email: ctchosney@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
[go](http://stackoverflow.com){:target="_blank" rel="noopener"}
