title: Craig T. Chosney
logo: /assets/img/IMG_1068.jpg
description: Current Manager with expert team leadership, planning, and organizational skills working toward Masters Degree in Quantitative Methods seeking opportunity to pivot career to data analytics
show_downloads: true
theme: jekyll-theme-minimal
